### ISSUE TITLE
Ariadna Monserrat López Aparicio

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Ariadnamonserrat10#1]
![Mapa mental actividad 1](https://user-images.githubusercontent.com/112223282/188047412-9245b9fa-2589-4f3d-a260-730e9c80c36c.png)
Ariadna Monserrat López Aparicio
1BS

**Comment by AmeliReyesHernandez** [comment]
18.4 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
